/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Academic Organizer API
 * API para gerenciamento de tarefas, disciplinas e rotina acadêmica
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type PostTasksBodyPriority =
  (typeof PostTasksBodyPriority)[keyof typeof PostTasksBodyPriority];

export const PostTasksBodyPriority = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
} as const;

export type PostTasksBody = {
  /** @minLength 1 */
  title: string;
  description?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  dueDate?: string;
  priority: PostTasksBodyPriority;
  subjectId?: string;
};

export type PostTasks201Priority =
  (typeof PostTasks201Priority)[keyof typeof PostTasks201Priority];

export const PostTasks201Priority = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
} as const;

export type PostTasks201 = {
  id: string;
  title: string;
  /** @nullable */
  description: string | null;
  completed: boolean;
  /** @nullable */
  dueDate: string | null;
  priority: PostTasks201Priority;
  /** @nullable */
  subjectId: string | null;
};

export type PostTasks400 = {
  error: string;
  code: string;
};

export type PostTasks401 = {
  error: string;
  code: string;
};

export type PostTasks500 = {
  error: string;
  code: string;
};

export type GetTasks200ItemPriority =
  (typeof GetTasks200ItemPriority)[keyof typeof GetTasks200ItemPriority];

export const GetTasks200ItemPriority = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
} as const;

export type GetTasks200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  title: string;
  description?: string;
  completed: boolean;
  priority: GetTasks200ItemPriority;
};

export type GetTasks401 = {
  error: string;
  code: string;
};

export type GetTasks500 = {
  error: string;
  code: string;
};

export type GetTasksTaskId200Priority =
  (typeof GetTasksTaskId200Priority)[keyof typeof GetTasksTaskId200Priority];

export const GetTasksTaskId200Priority = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
} as const;

export type GetTasksTaskId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  title: string;
  description?: string;
  completed: boolean;
  priority: GetTasksTaskId200Priority;
  dueDate?: string;
};

export type GetTasksTaskId401 = {
  error: string;
  code: string;
};

export type GetTasksTaskId404 = {
  error: string;
  code: string;
};

export type GetTasksTaskId500 = {
  error: string;
  code: string;
};

export type PatchTasksTaskIdComplete200Priority =
  (typeof PatchTasksTaskIdComplete200Priority)[keyof typeof PatchTasksTaskIdComplete200Priority];

export const PatchTasksTaskIdComplete200Priority = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
} as const;

export type PatchTasksTaskIdComplete200 = {
  id: string;
  title: string;
  /** @nullable */
  description: string | null;
  completed: boolean;
  /** @nullable */
  dueDate: string | null;
  priority: PatchTasksTaskIdComplete200Priority;
  /** @nullable */
  subjectId: string | null;
};

export type PatchTasksTaskIdComplete401 = {
  error: string;
  code: string;
};

export type PatchTasksTaskIdComplete404 = {
  error: string;
  code: string;
};

export type PatchTasksTaskIdComplete500 = {
  error: string;
  code: string;
};

export type Get200 = {
  message: string;
};

export type postTasksResponse201 = {
  data: PostTasks201;
  status: 201;
};

export type postTasksResponse400 = {
  data: PostTasks400;
  status: 400;
};

export type postTasksResponse401 = {
  data: PostTasks401;
  status: 401;
};

export type postTasksResponse500 = {
  data: PostTasks500;
  status: 500;
};

export type postTasksResponseSuccess = postTasksResponse201 & {
  headers: Headers;
};
export type postTasksResponseError = (
  postTasksResponse400 | postTasksResponse401 | postTasksResponse500
) & {
  headers: Headers;
};

export type postTasksResponse =
  postTasksResponseSuccess | postTasksResponseError;

export const getPostTasksUrl = () => {
  return `/tasks/`;
};

export const postTasks = async (
  postTasksBody: PostTasksBody,
  options?: RequestInit,
): Promise<postTasksResponse> => {
  return customFetch<postTasksResponse>(getPostTasksUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postTasksBody),
  });
};

export type getTasksResponse200 = {
  data: GetTasks200Item[];
  status: 200;
};

export type getTasksResponse401 = {
  data: GetTasks401;
  status: 401;
};

export type getTasksResponse500 = {
  data: GetTasks500;
  status: 500;
};

export type getTasksResponseSuccess = getTasksResponse200 & {
  headers: Headers;
};
export type getTasksResponseError = (
  getTasksResponse401 | getTasksResponse500
) & {
  headers: Headers;
};

export type getTasksResponse = getTasksResponseSuccess | getTasksResponseError;

export const getGetTasksUrl = () => {
  return `/tasks/`;
};

export const getTasks = async (
  options?: RequestInit,
): Promise<getTasksResponse> => {
  return customFetch<getTasksResponse>(getGetTasksUrl(), {
    ...options,
    method: "GET",
  });
};

export type getTasksTaskIdResponse200 = {
  data: GetTasksTaskId200;
  status: 200;
};

export type getTasksTaskIdResponse401 = {
  data: GetTasksTaskId401;
  status: 401;
};

export type getTasksTaskIdResponse404 = {
  data: GetTasksTaskId404;
  status: 404;
};

export type getTasksTaskIdResponse500 = {
  data: GetTasksTaskId500;
  status: 500;
};

export type getTasksTaskIdResponseSuccess = getTasksTaskIdResponse200 & {
  headers: Headers;
};
export type getTasksTaskIdResponseError = (
  | getTasksTaskIdResponse401
  | getTasksTaskIdResponse404
  | getTasksTaskIdResponse500
) & {
  headers: Headers;
};

export type getTasksTaskIdResponse =
  getTasksTaskIdResponseSuccess | getTasksTaskIdResponseError;

export const getGetTasksTaskIdUrl = (taskId: string) => {
  return `/tasks/${taskId}`;
};

export const getTasksTaskId = async (
  taskId: string,
  options?: RequestInit,
): Promise<getTasksTaskIdResponse> => {
  return customFetch<getTasksTaskIdResponse>(getGetTasksTaskIdUrl(taskId), {
    ...options,
    method: "GET",
  });
};

export type patchTasksTaskIdCompleteResponse200 = {
  data: PatchTasksTaskIdComplete200;
  status: 200;
};

export type patchTasksTaskIdCompleteResponse401 = {
  data: PatchTasksTaskIdComplete401;
  status: 401;
};

export type patchTasksTaskIdCompleteResponse404 = {
  data: PatchTasksTaskIdComplete404;
  status: 404;
};

export type patchTasksTaskIdCompleteResponse500 = {
  data: PatchTasksTaskIdComplete500;
  status: 500;
};

export type patchTasksTaskIdCompleteResponseSuccess =
  patchTasksTaskIdCompleteResponse200 & {
    headers: Headers;
  };
export type patchTasksTaskIdCompleteResponseError = (
  | patchTasksTaskIdCompleteResponse401
  | patchTasksTaskIdCompleteResponse404
  | patchTasksTaskIdCompleteResponse500
) & {
  headers: Headers;
};

export type patchTasksTaskIdCompleteResponse =
  | patchTasksTaskIdCompleteResponseSuccess
  | patchTasksTaskIdCompleteResponseError;

export const getPatchTasksTaskIdCompleteUrl = (taskId: string) => {
  return `/tasks/${taskId}/complete`;
};

export const patchTasksTaskIdComplete = async (
  taskId: string,
  options?: RequestInit,
): Promise<patchTasksTaskIdCompleteResponse> => {
  return customFetch<patchTasksTaskIdCompleteResponse>(
    getPatchTasksTaskIdCompleteUrl(taskId),
    {
      ...options,
      method: "PATCH",
    },
  );
};

export type getResponse200 = {
  data: Get200;
  status: 200;
};

export type getResponseSuccess = getResponse200 & {
  headers: Headers;
};
export type getResponse = getResponseSuccess;

export const getGetUrl = () => {
  return `/`;
};

/**
 * Hello World
 */
export const get = async (options?: RequestInit): Promise<getResponse> => {
  return customFetch<getResponse>(getGetUrl(), {
    ...options,
    method: "GET",
  });
};
